### ISSUE TITLE
Error when adding new images to run

### ISSUE THREAD

**Issue by ddobie** [askap-vast/vast-pipeline#718]
Run is https://dev.pipeline.vast-survey.org/piperuns/77/, with log file `2024-06-26-05-36-59_log.txt`

Traceback is
```
2024-06-26 07:01:03,006 runpipeline ERROR Processing error:
No objects to concatenate
Traceback (most recent call last):
  File "/usr/src/vast-pipeline/vast-pipeline-add-further-debug-logging/vast_pipeline/management/commands/runpipeline.py", line 340, in run_pipe
    pipeline.process_pipeline(p_run)
  File "/usr/src/vast-pipeline/vast-pipeline-add-further-debug-logging/vast_pipeline/pipeline/main.py", line 196, in process_pipeline
    sources_df = parallel_association(
  File "/usr/src/vast-pipeline/vast-pipeline-add-further-debug-logging/vast_pipeline/pipeline/association.py", line 1604, in parallel_association
    dd.from_pandas(images_df.set_index('skyreg_group'), npartitions=npartitions)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/base.py", line 292, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/base.py", line 575, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/multiprocessing.py", line 220, in get
    result = get_async(
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/local.py", line 508, in get_async
    raise_exception(exc, tb)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/local.py", line 221, in execute_task
    result = _execute_task(task, data)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/utils.py", line 39, in apply
    return func(*args, **kwargs)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/dataframe/core.py", line 6350, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/dask/dataframe/groupby.py", line 170, in _groupby_slice_apply
    return g.apply(func, *args, **kwargs)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1414, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1455, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 761, in apply
    res = f(group)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1388, in f
    return func(g, *args, **kwargs)
  File "/usr/src/vast-pipeline/vast-pipeline-add-further-debug-logging/vast_pipeline/pipeline/association.py", line 1143, in association
    sources_df, skyc1_srcs = reconstruct_associtaion_dfs(
  File "/usr/src/vast-pipeline/vast-pipeline-add-further-debug-logging/vast_pipeline/pipeline/utils.py", line 1549, in reconstruct_associtaion_dfs
    measurements = pd.concat(
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/usr/src/vast-pipeline/.venv/vast-pipeline-B4hVHlAK-py3.8/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by ddobie** [comment]
I've just tried to reproduce this in a local environment by running with data of the form
```
/import/ruby1/askap/PILOT/release/EPOCH0*/TILES/STOKESI_IMAGES/image.i.*VAST_0530-68*.fits
```
and then updating the config file to also add data of the form
```
/import/ruby1/askap/PILOT/release/EPOCH1*/TILES/STOKESI_IMAGES/image.i.*VAST_0530-68*.fits
```.

I'm using fairly standard settings, with forced fitting turned off (which I thought may be the root cause of the issue given I haven't seen it occur for runs with forced fits.

I'm unable to reproduce the issue, so it may be something that only occurs with larger runs. I have added some more debug statements in #725 to hopefully make fixing this easier if it occurs again.

**Comment by ddobie** [comment]
Complete speculation, but I think this _might_ be occurring when you add new images to the run, but not every field has a new image added. Will need to investigate further.

**Comment by ddobie** [comment]
Investigated further and the above doesn't seem to be the explanation

**Comment by ajstewart** [comment]
This error only occurs when this list is empty or full of non-dataframe objects:

https://github.com/askap-vast/vast-pipeline/blob/e5ebfb86500997f01db9166ea2e48038057deda1/vast_pipeline/pipeline/utils.py#L1546-L1548

So I would have a guess that `img_meas_paths` is empty. Were these log messages in place when this error happened?

https://github.com/askap-vast/vast-pipeline/blob/e5ebfb86500997f01db9166ea2e48038057deda1/vast_pipeline/pipeline/utils.py#L1489-L1497

I'd possibly be suspicious of the `images_df_done` that is being passed in here:

https://github.com/askap-vast/vast-pipeline/blob/e5ebfb86500997f01db9166ea2e48038057deda1/vast_pipeline/pipeline/association.py#L1141-L1142

Something corrupted or strange with the images in the large run that would cause that to not happen? Possibly none of the images are considered "done" so that list would be empty.

**Comment by ddobie** [comment]
I've encountered this error again and have found the root cause.

It occurs whenever you add an image to the pipeline run that isn't associated with an existing skyregion. The pipeline attempts to recreate the association dataframes from the existing run, but they don't exist because there's no observations of that part of the sky.

Solution is to check for that situation and set `add_mode=False` if it occurs.
